"""Initial migration

Revision ID: 613d519b3413
Revises: 
Create Date: 2024-09-25 13:08:05.040882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '613d519b3413'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conhecimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pergunta', sa.Text(), nullable=False),
    sa.Column('resposta', sa.Text(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('palavras_chave', sa.Text(), nullable=True),
    sa.Column('exemplo', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_categoria', 'conhecimento', ['categoria'], unique=False)
    op.create_index('idx_palavras_chave', 'conhecimento', ['palavras_chave'], unique=False)
    op.create_index('idx_pergunta', 'conhecimento', ['pergunta'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_pergunta', table_name='conhecimento')
    op.drop_index('idx_palavras_chave', table_name='conhecimento')
    op.drop_index('idx_categoria', table_name='conhecimento')
    op.drop_table('conhecimento')
    # ### end Alembic commands ###
